os_window_title Pi
os_window_name Pi

cd ~/srv/rpi4
layout fat:bias=80
launch --hold --title "Serial console" picocom /dev/ttyACM0 --imap=lfcrlf -b 115200 -g /home/s/pi-serial.log
launch --hold --title "TFTP server" sudo atftpd --trace --daemon --no-fork --user root.root --logfile /dev/stderr .
focus
launch --hold --title "skvm" env MANGOHUD=0 /home/s/src/skvm/main.py /dev/video0 /dev/ttyUSB0

# launch --hold fish -c 'watch -n 0.5 ddcutil --bus=6 setvcp 60 0x11'
# launch --hold kscreen-doctor output.DP-3.disable
